from lib.imports import *

class Login:
    USERNAME = '//*[@id="app__container"]//input[@id="username"]'
    PASSWORD = '//*[@id="app__container"]//input[@id="password"]'
    SIGN_BTN = '//*[@id="app__container"]//div[@class="login__form_action_container "]/button[contains(normalize-space(), "Sign in")]'
class Code:
    Search_Bar = '//*[@aria-label="Search"]'
    Post_fil = '//button[contains(normalize-space(), "Posts")]'
    Sort_By = '//button[contains(normalize-space(), "Sort by")]'
    Latest_post = '//*[@class="display-flex"][contains(normalize-space(), "Latest")]'
    Latest_post_btn = '(//button[contains(normalize-space(), "Show results")])[1]'
    Date_posted = '//button[contains(normalize-space(), "Date posted")]'
    past_24_hours = '//*[@class="display-flex"][contains(normalize-space(), "Past 24 hours")]'
    past_24_hours_btn = '(//button[contains(normalize-space(), "Show results")])[2]'
    first_post_cmnt = '(//*[@id="fie-impression-container"])[1]//button[contains(normalize-space(), "Comment")]'
    cmnt_box = '(//*[@id="fie-impression-container"])[1]//*[@data-placeholder="Add a comment…"]'
    post_btn = '(//button[contains(normalize-space(), "Post")])[2]'
    cmnt_btn = '//*[@class="display-flex align-items-center"]//button[contains(normalize-space(), "Comment")]'
    security_check = '//h1[contains(normalize-space(), "Let’s do a quick security check")]'
    security_code = '//h1[contains(normalize-space(), "Enter the code you see on your authenticator app")]'
    security_code_input = '(//*[contains(normalize-space(), "Enter the code you see on your authenticator app")]//*[@name="pin"])[1]'
    main_feed = '//*[@aria-label="Main Feed"]'
    security_code_submit_btn = '(//button[contains(normalize-space(), "Submit")])[1]'
    like_btn = '(//*[@id="fie-impression-container"])[1]//button[contains(normalize-space(), "Like")]'
    Read_article = '//*[@id="fie-impression-container"]//button[contains(normalize-space(), "Read article")]'
    con_acc_btn = '//button[contains(normalize-space(), "Accept")]'
    con_acc_reply_btn = '(//*[@class="invitation-card__custom-message-container"]//button)[2]'
    message_container = '//*[@aria-label="Write a message…"]'
    message_send_btn = '//*[@aria-label="Messaging"]//button[contains(normalize-space(), "Send")]'
    pending_invitaton = '//li[@data-view-name="pending-invitation"]'
    message_container_cross = '(//*[@class="relative display-flex flex-column flex-grow-1"]//button[@class="msg-overlay-bubble-header__control artdeco-button artdeco-button--circle artdeco-button--muted artdeco-button--1 artdeco-button--tertiary ember-view"])[1]'
    discard_btn = '//button[contains(normalize-space(), "Discard")]'
